--USUARIO DE BANCO DE DADOS--
SHOW USER;

/*
TABELA DUMMY | DUAL

No Oracle, tudo tem que vir de alguma tabela para o comando SELECT funcionar; para isso usa-se a tabela DUMMY.

Exemplo:

SELECT 1 + 1 AS SOMA FROM DUAL;
*/

--VERIFICAR AMBIENTE--
SELECT METADATA FROM SYS.KOPM$;
--B023 -> 32 BITS
--B047 -> 64 BITS

--DICIONÁRIO DE DADOS--
SELECT * FROM DICT;

--VERIFICAR SE A INSTÂNCIA É UNICA OU RAC--
SELECT PARALLEL FROM V$INSTANCE;
--PAR -> NO (INSTANCIA UNICA)
--PAR -> YES (RAC)

--VERIFICAR ESTRUTURA DE MEMÓRIA--
SELECT COMPONENT, CURRENT_SIZE, MIN_SIZE, MAX_SIZE
FROM V$SGA_DYNAMIC_COMPONENTS;

--CONECTANDO A OUTRO BANCO DE DADOS--
SQLPLUS SYSTEM/SENHA@NOMEDOBANCO

--VERIFICAR NOME DE BANCOS DE DADOS--
SELECT NAME FROM V$DATABASE;

--VERIFICAR VERSÃO DO BANCO DE DADOS--
SELECT BANNER FROM V$VERSION;

--VERIFICAR PROVILÉGIO DOS USUÁRIOS--
SELECT * FROM USER_SYS_PRIVS;

--VERIFICAR TABELAS DO USUARIO--
SELECT TABLE_NAME FROM USER_TABLES;

/*
ARMAZENAMENTO
LÓGICO - TABLESPACES -> SEGMENTOS (OBJETOS) -> EXTENSÕES (ESPAÇO) -> BLOCOS (DO SISTEMA OPERACIONAL)

FÍSICO -> DATAFILES

NÃO PODEMOS DETERMINAR EM QUAL ARQUIVO FÍSICO UM OBJETO FICARÁ.
*/

CREATE TABLE CURSOS(
	IDTESTE INT,
	NOME VARCHAR2(30),
	CARGA INT
)TABLESPACE USERS;

CREATE TABLE TESTE(
	IDTESTE INT,
	NOME VARCHAR2(30)
);

SELECT TABLE_NAME, TABLESPACE_NAME
FROM USER_TABLES;

SELECT TABLE_NAME, TABLESPACE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'CURSOS';

SELECT TABLE_NAME, TABLESPACE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'TESTE';

/*
TODO OBJETO É CRIADO POR PADRÃO NA TABLESPACE USERS, EXCETO QUANDO SE ESTÁ LOGADO COM O USUÁRIO SYSTEM; NESTE, O OBJETO SERÁ CRIADO NA TABLESPACE SYSTEM.
*/

SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME,
BYTES, BLOCKS, EXTENTS
FROM USER_SEGMENTS 
WHERE SEGMENT_NAME = 'CURSOS';

--FORMATAÇÃO DE COLUNAS--
COLUMN TABLESPACE_NAME FORMAT A10; -- A10 É O NÚMERO DE CARACTERES
COLUMN SEGMENT_NAME FORMAT A10;
COLUMN SEGMENT_TYPE FORMAT A10;

