--USUARIO DE BANCO DE DADOS--
SHOW USER;

/*
TABELA DUMMY | DUAL

No Oracle, tudo tem que vir de alguma tabela para o comando SELECT funcionar; para isso usa-se a tabela DUMMY.

Exemplo:

SELECT 1 + 1 AS SOMA FROM DUAL;
*/

--VERIFICAR AMBIENTE--
SELECT METADATA FROM SYS.KOPM$;
--B023 -> 32 BITS
--B047 -> 64 BITS

--DICIONÁRIO DE DADOS--
SELECT * FROM DICT;

--VERIFICAR SE A INSTÂNCIA É UNICA OU RAC--
SELECT PARALLEL FROM V$INSTANCE;
--PAR -> NO (INSTANCIA UNICA)
--PAR -> YES (RAC)

--VERIFICAR ESTRUTURA DE MEMÓRIA--
SELECT COMPONENT, CURRENT_SIZE, MIN_SIZE, MAX_SIZE
FROM V$SGA_DYNAMIC_COMPONENTS;

--CONECTANDO A OUTRO BANCO DE DADOS--
SQLPLUS SYSTEM/SENHA@NOMEDOBANCO

--VERIFICAR NOME DE BANCOS DE DADOS--
SELECT NAME FROM V$DATABASE;

--VERIFICAR VERSÃO DO BANCO DE DADOS--
SELECT BANNER FROM V$VERSION;

--VERIFICAR PROVILÉGIO DOS USUÁRIOS--
SELECT * FROM USER_SYS_PRIVS;

--VERIFICAR TABELAS DO USUARIO--
SELECT TABLE_NAME FROM USER_TABLES;