--DEFERRABLE CONSTRAINTS

CREATE TABLE FUNCIONARIO(
    IDFUNCIONARIO INT CONSTRAINT PF_FUNCIONARIO PRIMARY KEY,
    NOME VARCHAR2(100)
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY,
    NUMERO VARCHAR2(10),
    ID_FUNCIONARIO INT
);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO;

INSERT INTO FUNCIONARIO VALUES (1, 'MAURICIO');
INSERT INTO TELEFONE VALUES (10, '34342454',1);

/*
A CONSTRAINT DE INTEGRIDADE REFERENCIAL (FK), CHECA A INTEGRIDADE LOGO APÓS
O COMANDO DE DML (INSERT, UPDATE, DELETE) - NÃO POSSIBILITANDO ASSIM A INSERÇÃO
 DE REGISTROS SEM REFERENCIA.
*/

--Verificando estado das CONSTRAINTS
SELECT CONSTRAINT_NAME, DEFERRABLE, DEFERRED
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('FUNCIONARIO','TELEFONE');

/*
DEFERRABLE - Informa se a verificação pode ou não ser atrasada
Se não (NOT DEFERRABLE, vai ser checada na DML)
Se sim (DEFERRABLE), na DML ou na DTL, o padrão é na DML

DEFERRED - Se vai ser VERIFICADA na hora da DML ou na hora da DML, o padrão é DML
*/

--Deletando uma CONSTRAINT
ALTER TABLE TELEFONE DROP CONSTRAINT FK_TELEFONE;

--Recriando a CONSTRAINT com outro STATUS
ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO
DEFERRABLE; --Informando que a checagem pode ser atrasada

--Mudando para a DTL
SET CONSTRAINTS ALL DEFERRED;

/*
APÓS AS ALTERAÇÕES, NO MOMENTO DO COMMIT É VERIFICADA A INTEGRIDADE, SE NÃO
HOUVER REFERENCIA, É FEITO ROLLBACK NAS INSERÇÕES FEITAS.
*/

SELECT CONSTRAINT_NAME, DEFERRABLE AS ATRASADA, DEFERRED AS VERIFICACAO
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('FUNCIONARIO','TELEFONE');





